language: node_js
node_js:
  - '8'
  - '10'
cache:
  yarn: true
  directories:
    - 'node_modules'

script:
  - npm run lint
  - npm test

after_success:
  - npm run build
  - npm run build:tilecloud

deploy:
  provider: script
  script: 'echo "//registry.npmjs.org/:_authToken=${API_TOKEN}" > $HOME/.npmrc && npm publish --access=public'
  on:
    tags: true
    condition: $TRAVIS_NODE_VERSION = 10
  skip_cleanup: true

notifications:
  email: false
