name: Deploy to CDN

on:
  push:
    branches: [ master, 'v[0-9]+' ]
    tags: [ 'v*' ]
    pull_request:
      branches: [ 'v[0-9]+' ]

jobs:
  build:
    runs-on: ubuntu-latest

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Restore timestamps
        uses: chetan/git-restore-mtime-action@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::762706324393:role/github-actions-cdn-geolonia-deploy

      - name: Deploy to S3
        run: |
          # Note: The default max-age is set at 3600 seconds or 1 hour. After 1 hour,
          # the client will mark the resource as stale, and require a refresh.
          # In most cases, this will result in a if-modified-since conditional request.

          # For resources that are immutable (for example, embed-chunks), the max-age is set to immutable.
          # For resources that will be manually invalidated, an addition s-maxage so CloudFront keeps the file in its cache as long as possible.

          # Deploy embed chunks -- because they have fingerprints in the filename, they're immutable
          aws s3 sync ./public/v${{ steps.version.outputs.major_version }}/embed-chunks s3://gl-cdn-ap-northeast-1/v${{ steps.version.outputs.major_version }}/embed-chunks --cache-control "public,max-age=31536000,immutable"
          aws s3 sync ./public/v${{ steps.version.outputs.version }}/embed-chunks s3://gl-cdn-ap-northeast-1/v${{ steps.version.outputs.version }}/embed-chunks --cache-control "public,max-age=31536000,immutable"

          # Deploy main embed entrypoint
          # I used to use s-maxage here, but after testing decided to revert back to only using max-age.
          # If you use s-maxage that is much longer than max-age, the age header will be longer than
          # max-age, and the browser will think that the file is expired. Using max-age will make
          # CloudFront fetch a new file every 3600 seconds, resetting the Age header
          aws s3 cp ./public/v${{ steps.version.outputs.major_version }}/embed s3://gl-cdn-ap-northeast-1/v${{ steps.version.outputs.major_version }}/embed --cache-control "public,max-age=3600" --content-type "application/javascript; charset=UTF-8"
          aws s3 cp ./public/v${{ steps.version.outputs.version }}/embed s3://gl-cdn-ap-northeast-1/v${{ steps.version.outputs.version }}/embed --cache-control "public,max-age=3600" --content-type "application/javascript; charset=UTF-8"

          aws cloudfront create-invalidation --distribution-id "E1ZFNBWBSCLVFC" --paths "/v${{ steps.version.outputs.major_version }}/embed" "/v${{ steps.version.outputs.version }}/embed"
